### PR TITLE
Refactor image schemas and test cases

### PR DESCRIPTION
**Pull request by rintooo**
Diff
```
1. Deleted unnecessary environment variables.
2. Deleted unnecessary functions.
3. Changed resource schema parameters.
4. Changed test step according to the our rules.
```

Confirmed all tests passed.

### CODE REVIEW

**Comment by keiichi-hikita** [comment]
In TestAccImageStoragesV2ImageTags, I try to add one test step like below, but result was failed.

Added test step.
```
			resource.TestStep{
				Config: testAccImageStoragesV2ImageTags4,
				Check: resource.ComposeTestCheckFunc(
					testAccCheckImageStoragesV2ImageExists("ecl_imagestorages_image_v2.image_1", &image),
					testAccCheckImageStoragesV2ImageTagCount("ecl_imagestorages_image_v2.image_1", 0),
				),
			},
```

Corresponding configuration is like ...
```
var testAccImageStoragesV2ImageTags4 = fmt.Sprintf(`
  resource "ecl_imagestorages_image_v2" "image_1" {
      name   = "Temp Terraform AccTest"
      local_file_path = "%s"
      container_format = "bare"
      disk_format = "qcow2"
  }`, localFileForResourceTest)
```

This configuration means "remove tags" in Terraform world, but lead to "Bad Request" at Glance API side.

Request
```
PATCH /v2/images/fc89e6f6-6771-4df1-a1a6-b76647603cb6 HTTP/1.1
Host: glance-jp4-ecl.api.ntt.com
User-Agent: Terraform/0.11.10 eclcloud/1.0.0
Connection: close
Content-Length: 46
Accept: application/json
Content-Type: application/openstack-images-v2.1-json-patch
X-Auth-Token: 25045a8aa08d49fd9035420bc8ee4231
Accept-Encoding: gzip

[{"op":"replace","path":"/tags","value":null}]
```

Response
```
400 Bad Request

Provided object does not match schema 'image': None is not of type 'array'  Failed validating 'type' in schema['properties']['tags']:     {'description': u'List of strings related to the image',      'items': {'maxLength': 255, 'type': 'string'},      'type': 'array'}  On instance['tags']:     None
```

This is same if change configuration like below. (empty list)
```
var testAccImageStoragesV2ImageTags4 = fmt.Sprintf(`
  resource "ecl_imagestorages_image_v2" "image_1" {
      name   = "Temp Terraform AccTest"
      local_file_path = "%s"
      container_format = "bare"
      disk_format = "qcow2"
      tags = []
  }`, localFileForResourceTest)
```

It means user can not make tags blank(remove all), so I think it need to be fixed.

**Comment by keiichi-hikita** [comment]
Another comment:

I think it may be better to add constraint for member status to restrict input only  in "accepted", "rejected".(Same as license_switch, but not necessary)

**Comment by keiichi-hikita** [comment]
Sorry, I made mistake to close this PR.(already re-opened...)

**Comment by rintooo** [comment]
Thank you for your comment. Fixed above 2 issues.
```
1. Make enabled to change Tags with empty slice.
2. Add ValidateFunc for "status" in member accepter resource.
```

Confirmed all tests passed.
```
NW7-RINTO-MAC:terraform-provider-ecl nttcom$ TF_ACC=1 go test ./ecl/ -run=TestAccImageStoragesV2 -count=1 -timeout 120m -v
=== RUN   TestAccImageStoragesV2ImageDataSourceBasic
--- PASS: TestAccImageStoragesV2ImageDataSourceBasic (24.99s)
=== RUN   TestAccImageStoragesV2ImageImportBasic
--- PASS: TestAccImageStoragesV2ImageImportBasic (22.24s)
=== RUN   TestAccImageStoragesV2ImageBasic
--- PASS: TestAccImageStoragesV2ImageBasic (19.26s)
=== RUN   TestAccImageStoragesV2ImageName
--- PASS: TestAccImageStoragesV2ImageName (36.38s)
=== RUN   TestAccImageStoragesV2ImageTags
--- PASS: TestAccImageStoragesV2ImageTags (38.99s)
=== RUN   TestAccImageStoragesV2ImageLicenseSwitch
--- PASS: TestAccImageStoragesV2ImageLicenseSwitch (19.27s)
=== RUN   TestAccImageStoragesV2ImageProperties
--- PASS: TestAccImageStoragesV2ImageProperties (48.88s)
=== RUN   TestAccImageStoragesV2MemberAccepterBasic
--- PASS: TestAccImageStoragesV2MemberAccepterBasic (44.11s)
=== RUN   TestAccImageStoragesV2MemberAccepterInvalidStatus
--- PASS: TestAccImageStoragesV2MemberAccepterInvalidStatus (0.01s)
=== RUN   TestAccImageStoragesV2MemberBasic
--- PASS: TestAccImageStoragesV2MemberBasic (30.64s)
PASS
ok  	github.com/ngpf-public/terraform-provider-ecl/ecl	284.813s
```

Validation for "license_switch" has been already implemented.
I did check its ValidateFunc working correctly.
```
NW7-RINTO-MAC:terraform-provider-ecl nttcom$ TF_ACC=1 go test ./ecl/ -run=TestValidateLicenseSwitch -count=1 -timeout 120m -v
=== RUN   TestValidateLicenseSwitch
--- PASS: TestValidateLicenseSwitch (0.00s)
PASS
ok  	github.com/ngpf-public/terraform-provider-ecl/ecl	0.028s
```

**Pull request merged**
